#!/usr/bin/env python3
"""Run the mandatory non-destructive numerical validation suite.

The command exits non-zero when a mandatory check fails.  Generated bytecode
and plotting caches are redirected to a temporary directory by the caller or
disabled, so the scientific result directories are not modified.
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import sys
import tempfile
import unittest


def restart_with_reproducible_environment() -> None:
    """Start Python again so hash and BLAS settings apply before imports."""

    if os.environ.get("SCHA_VALIDATION_BOOTSTRAPPED") == "1":
        return
    environment = os.environ.copy()
    environment.update(
        {
            "SCHA_VALIDATION_BOOTSTRAPPED": "1",
            "PYTHONDONTWRITEBYTECODE": "1",
            "PYTHONHASHSEED": "0",
            "OMP_NUM_THREADS": "1",
            "OPENBLAS_NUM_THREADS": "1",
            "MKL_NUM_THREADS": "1",
        }
    )
    os.execve(
        sys.executable,
        [sys.executable, str(Path(__file__).resolve()), *sys.argv[1:]],
        environment,
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--quick",
        action="store_true",
        help="Skip the four costly production-grid and Matsubara convergence checks.",
    )
    args = parser.parse_args()
    restart_with_reproducible_environment()

    python_root = Path(__file__).resolve().parent
    repository_root = python_root.parent
    if not args.quick:
        os.environ["SCHA_VALIDATION_FULL"] = "1"
    else:
        os.environ.pop("SCHA_VALIDATION_FULL", None)

    with tempfile.TemporaryDirectory(prefix="scha-validation-") as directory:
        temporary_root = Path(directory)
        os.environ["MPLCONFIGDIR"] = str(temporary_root / "matplotlib")
        os.environ["XDG_CACHE_HOME"] = str(temporary_root / "cache")
        os.chdir(repository_root)
        suite = unittest.defaultTestLoader.discover(
            str(python_root / "tests"),
            pattern="test_*.py",
            top_level_dir=str(repository_root),
        )
        suite.addTests(unittest.TestLoader().discover(
            str(python_root / "Mayer"), pattern="test_*.py"
        ))
        result = unittest.TextTestRunner(verbosity=2).run(suite)
        return 0 if result.wasSuccessful() else 1


if __name__ == "__main__":
    raise SystemExit(main())
